# Generated by Django 5.0.6 on 2024-06-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_func", "0004_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank="True", max_length=100),
        ),
    ]
