# Generated by Django 5.0.6 on 2024-06-20 05:24

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_func", "0005_alter_profile_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("caption", models.TextField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("no_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
